version: '3.7'
services:
  sdav-jupyter:
    build:
      context: ../
      dockerfile: .docker/jupyter.Dockerfile
    environment:
      - TZ:Asia/Tokyo
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    env_file: .env
    volumes:
      - ../notebooks:/home/jovyan
    ports:
      - "8888:8888"
    container_name: sdav-jupyter

  sdav-gateway:
    build:
      context: ../
      dockerfile: .docker/kernel_gateway.Dockerfile
    volumes:
      - ../notebooks/api:/home/jovyan
    ports:
      - "8889:8889"
    container_name: sdav-gateway

  sdav-proxy:
    image: nginx:1.15.8-alpine
    environment:
      LANG: ja_JP.UTF-8
    volumes:
      - ./conf/dev/50x.html:/usr/share/nginx/html/50x.html
      - ./conf/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./fake_htpasswd:/etc/nginx/htpasswd
    ports:
      - "${PORT}:80"
    container_name: sdav-proxy
    links:
      - sdav-gateway

